apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:latest
        ports:
        - containerPort: 5153
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking-db-postgresql
              key: postgres-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: DB_NAME
      imagePullSecrets:
      - name: ecr-registry-secret
