apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
data:
  DB_USERNAME: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mydatabase"
